const mongoose=require('mongoose');
const courseModel=new mongoose.Schema({
    courseName:{
        type:String
    },
    courseDescription:{
        type:String
    },
    instructor:{
        type:mongoose.Types.ObjectId,
        ref:'User',
        required:true
    },
    whatYouWillLearn:{
        type:String
    },
    courseContent:[
        {
            type:mongoose.Types.ObjectId,
            ref:'Section'
        }
    ],
    ratingAndReviews:[{
        type:mongoose.Types.ObjectId,
        ref:'RatingAndReview'
    }],
    price:{
        type:Number
    },
    thumbnail:{
        type:String
    },
    tag:{
        type:[String],
        required:true
    },
    category:{
        type:mongoose.Types.ObjectId,
        ref:'Category'
    },
    studentEnrolled:[
        {
            type:mongoose.Types.ObjectId,
            ref:'User',
            required:true 
        }
    ],
    instructions: {
		type: [String],
	},
    status:{
		type:String,
		enum:["Draft","Published"]
	},
    createdAt: {
		type:Date,
		default:Date.now
	},
});
module.exports=mongoose.model('Course',courseModel);